
services:
  pyspark-notebook:
    build:
      context: .devcontainer
    ports:
      - "8888:8888"
    volumes:
      - ./:/work
    entrypoint: ["jupyter", "lab", "--ip=0.0.0.0", "--NotebookApp.token=cidaen", "--allow-root"]

    